import { prisma } from '../config/database.js';

// ─────────────────────────────────────────────────────────────
// TechKart curated catalog
// Real tech products spanning every budget band (₹1k → ₹2L) and
// category, so the assistant always has stock to recommend.
// Images are hotlink-friendly manufacturer / retailer CDN URLs.
// ─────────────────────────────────────────────────────────────
const SEEDED_PRODUCTS = [
  // ─────────────── LAPTOPS ───────────────
  {
    externalId: 'tk-001',
    title: 'Apple MacBook Pro 14" M3',
    description:
      'Apple M3 chip, 18GB RAM, 512GB SSD, Liquid Retina XDR display, 22-hour battery life. Built for professionals.',
    price: 189900,
    originalPrice: 209900,
    category: 'laptops',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/61lYIKPieDL._AC_.jpg',
    rating: 4.9,
    reviewCount: 2341,
    stock: 45,
    isFeatured: true,
    specs: { processor: 'Apple M3', ram: '18GB', storage: '512GB SSD', display: '14.2" Liquid Retina XDR', battery: '22 hours', weight: '1.55 kg', os: 'macOS' },
    tags: ['apple', 'laptop', 'premium', 'featured'],
  },
  {
    externalId: 'tk-006',
    title: 'Dell XPS 15 Intel Core i9',
    description:
      'Intel Core i9-13900H, 32GB DDR5, 1TB SSD, OLED 3.5K display, NVIDIA RTX 4060, Windows 11 Pro.',
    price: 179990,
    originalPrice: 199990,
    category: 'laptops',
    brand: 'Dell',
    imageUrl:
      'https://m.media-amazon.com/images/I/716T+1iVYqL._AC_SL1386_.jpg',
    rating: 4.7,
    reviewCount: 876,
    stock: 55,
    isFeatured: true,
    specs: { processor: 'Intel Core i9-13900H', ram: '32GB DDR5', storage: '1TB NVMe SSD', display: '15.6" OLED 3.5K', gpu: 'NVIDIA RTX 4060', os: 'Windows 11 Pro' },
    tags: ['dell', 'laptop', 'creator', 'premium'],
  },
  {
    externalId: 'tk-101',
    title: 'Apple MacBook Air 13" M2',
    description:
      'Apple M2 chip, 8GB unified memory, 256GB SSD, 13.6" Liquid Retina, fanless, up to 18-hour battery.',
    price: 94990,
    originalPrice: 99900,
    category: 'laptops',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/71kVRxJ4xmL._AC_.jpg',
    rating: 4.8,
    reviewCount: 4120,
    stock: 120,
    isFeatured: true,
    specs: { processor: 'Apple M2', ram: '8GB', storage: '256GB SSD', display: '13.6" Liquid Retina', battery: '18 hours', weight: '1.24 kg', os: 'macOS' },
    tags: ['apple', 'laptop', 'ultrabook'],
  },
  {
    externalId: 'tk-102',
    title: 'Apple MacBook Air 15" M3',
    description:
      'Apple M3 chip, 8GB unified memory, 512GB SSD, expansive 15.3" Liquid Retina display, 18-hour battery.',
    price: 134900,
    originalPrice: 144900,
    category: 'laptops',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/61bsMB7nq7L.jpg',
    rating: 4.8,
    reviewCount: 1530,
    stock: 70,
    isFeatured: false,
    specs: { processor: 'Apple M3', ram: '8GB', storage: '512GB SSD', display: '15.3" Liquid Retina', battery: '18 hours', weight: '1.51 kg', os: 'macOS' },
    tags: ['apple', 'laptop', 'ultrabook'],
  },
  {
    externalId: 'tk-103',
    title: 'Acer Aspire 3 Ryzen 5',
    description:
      'AMD Ryzen 5 7520U, 8GB RAM, 512GB SSD, 15.6" Full HD display. Reliable everyday laptop on a budget.',
    price: 32990,
    originalPrice: 42999,
    category: 'laptops',
    brand: 'Acer',
    imageUrl: 'https://m.media-amazon.com/images/I/61TWFbueNiL._AC_.jpg',
    rating: 4.2,
    reviewCount: 3890,
    stock: 200,
    isFeatured: false,
    specs: { processor: 'AMD Ryzen 5 7520U', ram: '8GB', storage: '512GB SSD', display: '15.6" Full HD', battery: '8 hours', os: 'Windows 11' },
    tags: ['acer', 'laptop', 'budget'],
  },
  {
    externalId: 'tk-104',
    title: 'Lenovo IdeaPad Slim 3',
    description:
      'Intel Core i5-12450H, 16GB RAM, 512GB SSD, 15.6" FHD, slim metallic build for work and study.',
    price: 46990,
    originalPrice: 58990,
    category: 'laptops',
    brand: 'Lenovo',
    imageUrl: 'https://m.media-amazon.com/images/I/81+SKGgJ9yL._AC_.jpg',
    rating: 4.3,
    reviewCount: 2210,
    stock: 150,
    isFeatured: false,
    specs: { processor: 'Intel Core i5-12450H', ram: '16GB', storage: '512GB SSD', display: '15.6" Full HD', battery: '9 hours', os: 'Windows 11' },
    tags: ['lenovo', 'laptop', 'value'],
  },
  {
    externalId: 'tk-105',
    title: 'HP Pavilion 14 Intel Core i5',
    description:
      'Intel Core i5-1334U, 16GB RAM, 512GB SSD, 14" FHD IPS, backlit keyboard, Windows 11 + MS Office.',
    price: 58990,
    originalPrice: 71999,
    category: 'laptops',
    brand: 'HP',
    imageUrl: 'https://m.media-amazon.com/images/I/7135j1ia3xL._AC_.jpg',
    rating: 4.4,
    reviewCount: 1670,
    stock: 110,
    isFeatured: false,
    specs: { processor: 'Intel Core i5-1334U', ram: '16GB', storage: '512GB SSD', display: '14" FHD IPS', battery: '10 hours', os: 'Windows 11' },
    tags: ['hp', 'laptop', 'thin-light'],
  },
  {
    externalId: 'tk-106',
    title: 'Acer Nitro V 15 Gaming',
    description:
      'Intel Core i5-13420H, 16GB RAM, 512GB SSD, NVIDIA RTX 4050 6GB, 15.6" 144Hz FHD gaming laptop.',
    price: 72990,
    originalPrice: 89999,
    category: 'laptops',
    brand: 'Acer',
    imageUrl: 'https://m.media-amazon.com/images/I/71Hiqi140OL._AC_.jpg',
    rating: 4.4,
    reviewCount: 940,
    stock: 80,
    isFeatured: true,
    specs: { processor: 'Intel Core i5-13420H', ram: '16GB', storage: '512GB SSD', gpu: 'NVIDIA RTX 4050 6GB', display: '15.6" 144Hz FHD', os: 'Windows 11' },
    tags: ['acer', 'laptop', 'gaming'],
  },
  {
    externalId: 'tk-107',
    title: 'Lenovo Legion 5 RTX 4060',
    description:
      'AMD Ryzen 7 7840HS, 16GB DDR5, 1TB SSD, NVIDIA RTX 4060 8GB, 15.6" WQXGA 165Hz. Serious gaming performance.',
    price: 109990,
    originalPrice: 134990,
    category: 'laptops',
    brand: 'Lenovo',
    imageUrl: 'https://m.media-amazon.com/images/I/81pZw2PXzLL._AC_.jpg',
    rating: 4.6,
    reviewCount: 1120,
    stock: 60,
    isFeatured: true,
    specs: { processor: 'AMD Ryzen 7 7840HS', ram: '16GB DDR5', storage: '1TB SSD', gpu: 'NVIDIA RTX 4060 8GB', display: '15.6" WQXGA 165Hz', os: 'Windows 11' },
    tags: ['lenovo', 'laptop', 'gaming', 'legion'],
  },
  {
    externalId: 'tk-108',
    title: 'ASUS ROG Strix G16',
    description:
      'Intel Core i7-13650HX, 16GB DDR5, 1TB SSD, NVIDIA RTX 4070 8GB, 16" QHD+ 240Hz. Esports-grade powerhouse.',
    price: 149990,
    originalPrice: 179990,
    category: 'laptops',
    brand: 'ASUS',
    imageUrl: 'https://m.media-amazon.com/images/I/71zuMSjwDfL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 680,
    stock: 40,
    isFeatured: false,
    specs: { processor: 'Intel Core i7-13650HX', ram: '16GB DDR5', storage: '1TB SSD', gpu: 'NVIDIA RTX 4070 8GB', display: '16" QHD+ 240Hz', os: 'Windows 11' },
    tags: ['asus', 'laptop', 'gaming', 'rog'],
  },

  // ─────────────── SMARTPHONES ───────────────
  {
    externalId: 'tk-002',
    title: 'Samsung Galaxy S24 Ultra',
    description:
      'Snapdragon 8 Gen 3, 12GB RAM, 256GB, 200MP camera, built-in S Pen, titanium frame. The ultimate Android flagship.',
    price: 134999,
    originalPrice: 149999,
    category: 'smartphones',
    brand: 'Samsung',
    imageUrl:
      'https://m.media-amazon.com/images/I/81vxWpPpgNL.jpg',
    rating: 4.8,
    reviewCount: 5632,
    stock: 120,
    isFeatured: true,
    specs: { processor: 'Snapdragon 8 Gen 3', ram: '12GB', storage: '256GB', camera: '200MP', display: '6.8" Dynamic AMOLED 2X', battery: '5000mAh', sPen: true },
    tags: ['samsung', 'smartphone', 'flagship'],
  },
  {
    externalId: 'tk-011',
    title: 'OnePlus 12 5G',
    description:
      'Snapdragon 8 Gen 3, 16GB RAM, 256GB, Hasselblad triple camera, 100W SuperVOOC charging.',
    price: 64999,
    originalPrice: 69999,
    category: 'smartphones',
    brand: 'OnePlus',
    imageUrl: 'https://m.media-amazon.com/images/I/81fRAoUL-fL.jpg',
    rating: 4.6,
    reviewCount: 3120,
    stock: 140,
    isFeatured: false,
    specs: { processor: 'Snapdragon 8 Gen 3', ram: '16GB', storage: '256GB', display: '6.82" QHD+ AMOLED', camera: '50MP Hasselblad', battery: '5400mAh' },
    tags: ['oneplus', 'smartphone', 'flagship'],
  },
  {
    externalId: 'tk-110',
    title: 'iPhone 15 Pro Max 256GB',
    description:
      'A17 Pro chip, titanium design, 6.7" Super Retina XDR, 5x telephoto, 48MP main camera, USB-C.',
    price: 159900,
    originalPrice: 164900,
    category: 'smartphones',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/815eN0AS-CL._AC_SL1500_.jpg',
    rating: 4.9,
    reviewCount: 6210,
    stock: 90,
    isFeatured: true,
    specs: { processor: 'A17 Pro', ram: '8GB', storage: '256GB', display: '6.7" Super Retina XDR', camera: '48MP + 12MP + 12MP', battery: '4422mAh' },
    tags: ['apple', 'iphone', 'flagship'],
  },
  {
    externalId: 'tk-111',
    title: 'iPhone 15 128GB',
    description:
      'A16 Bionic, Dynamic Island, 48MP main camera, 6.1" Super Retina XDR, USB-C, Ceramic Shield.',
    price: 69900,
    originalPrice: 79900,
    category: 'smartphones',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/71vKy5OHuPL.jpg',
    rating: 4.7,
    reviewCount: 4980,
    stock: 130,
    isFeatured: false,
    specs: { processor: 'A16 Bionic', ram: '6GB', storage: '128GB', display: '6.1" Super Retina XDR', camera: '48MP + 12MP', battery: '3349mAh' },
    tags: ['apple', 'iphone'],
  },
  {
    externalId: 'tk-112',
    title: 'Samsung Galaxy S24',
    description:
      'Snapdragon 8 Gen 3, 8GB RAM, 256GB, 50MP triple camera, 6.2" Dynamic AMOLED 120Hz, Galaxy AI.',
    price: 74999,
    originalPrice: 84999,
    category: 'smartphones',
    brand: 'Samsung',
    imageUrl:
      'https://m.media-amazon.com/images/I/61DLCeUzybL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 2870,
    stock: 110,
    isFeatured: false,
    specs: { processor: 'Snapdragon 8 Gen 3', ram: '8GB', storage: '256GB', display: '6.2" Dynamic AMOLED 120Hz', camera: '50MP + 12MP + 10MP', battery: '4000mAh' },
    tags: ['samsung', 'smartphone', 'flagship'],
  },
  {
    externalId: 'tk-113',
    title: 'Google Pixel 8a',
    description:
      'Google Tensor G3, 8GB RAM, 128GB, 64MP camera with AI photo tools, 6.1" Actua 120Hz OLED, 7 years updates.',
    price: 52999,
    originalPrice: 59999,
    category: 'smartphones',
    brand: 'Google',
    imageUrl: 'https://m.media-amazon.com/images/I/71XOyJfGIzL._AC_SL1500_.jpg',
    rating: 4.5,
    reviewCount: 1340,
    stock: 95,
    isFeatured: false,
    specs: { processor: 'Google Tensor G3', ram: '8GB', storage: '128GB', display: '6.1" Actua OLED 120Hz', camera: '64MP + 13MP', battery: '4492mAh' },
    tags: ['google', 'pixel', 'smartphone', 'camera'],
  },
  {
    externalId: 'tk-114',
    title: 'Samsung Galaxy A55 5G',
    description:
      'Exynos 1480, 8GB RAM, 128GB, 50MP OIS camera, 6.6" Super AMOLED 120Hz, IP67, Gorilla Glass Victus+.',
    price: 39999,
    originalPrice: 45999,
    category: 'smartphones',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/71qW2qMHOCL._AC_.jpg',
    rating: 4.3,
    reviewCount: 2050,
    stock: 160,
    isFeatured: false,
    specs: { processor: 'Exynos 1480', ram: '8GB', storage: '128GB', display: '6.6" Super AMOLED 120Hz', camera: '50MP OIS', battery: '5000mAh' },
    tags: ['samsung', 'smartphone', 'mid-range'],
  },
  {
    externalId: 'tk-115',
    title: 'Nothing Phone (2a)',
    description:
      'MediaTek Dimensity 7200 Pro, 8GB RAM, 128GB, dual 50MP camera, 6.7" AMOLED 120Hz, Glyph Interface.',
    price: 25999,
    originalPrice: 27999,
    category: 'smartphones',
    brand: 'Nothing',
    imageUrl: 'https://m.media-amazon.com/images/I/81wCjPXM7lL.jpg',
    rating: 4.4,
    reviewCount: 3410,
    stock: 180,
    isFeatured: true,
    specs: { processor: 'Dimensity 7200 Pro', ram: '8GB', storage: '128GB', display: '6.7" AMOLED 120Hz', camera: '50MP + 50MP', battery: '5000mAh' },
    tags: ['nothing', 'smartphone', 'mid-range'],
  },
  {
    externalId: 'tk-116',
    title: 'Realme Narzo 70 Pro 5G',
    description:
      'MediaTek Dimensity 7050, 8GB RAM, 128GB, 50MP Sony IMX890 OIS, 6.67" AMOLED 120Hz, 67W charging.',
    price: 17999,
    originalPrice: 21999,
    category: 'smartphones',
    brand: 'Realme',
    imageUrl: 'https://m.media-amazon.com/images/I/71ceFVAwe4L._SL1500_.jpg',
    rating: 4.2,
    reviewCount: 5120,
    stock: 220,
    isFeatured: false,
    specs: { processor: 'Dimensity 7050', ram: '8GB', storage: '128GB', display: '6.67" AMOLED 120Hz', camera: '50MP Sony IMX890 OIS', battery: '5000mAh' },
    tags: ['realme', 'smartphone', 'budget'],
  },
  {
    externalId: 'tk-117',
    title: 'Redmi 13C 5G',
    description:
      'MediaTek Dimensity 6100+, 4GB RAM, 128GB, 50MP camera, 6.74" HD+ 90Hz, 5000mAh battery.',
    price: 12999,
    originalPrice: 15999,
    category: 'smartphones',
    brand: 'Redmi',
    imageUrl: 'https://m.media-amazon.com/images/I/81Z1scL6HvL._SL1500_.jpg',
    rating: 4.1,
    reviewCount: 8920,
    stock: 300,
    isFeatured: false,
    specs: { processor: 'Dimensity 6100+', ram: '4GB', storage: '128GB', display: '6.74" HD+ 90Hz', camera: '50MP', battery: '5000mAh' },
    tags: ['redmi', 'smartphone', 'budget', '5g'],
  },

  // ─────────────── AUDIO ───────────────
  {
    externalId: 'tk-003',
    title: 'Sony WH-1000XM5 Headphones',
    description:
      'Industry-leading noise cancellation, 30-hour battery, multipoint connection, crystal clear hands-free calling.',
    price: 26990,
    originalPrice: 34990,
    category: 'audio',
    brand: 'Sony',
    imageUrl: 'https://m.media-amazon.com/images/I/71-z351XFQL._AC_.jpg',
    rating: 4.7,
    reviewCount: 8901,
    stock: 200,
    isFeatured: true,
    specs: { type: 'Over-ear', connectivity: 'Bluetooth 5.2', battery: '30 hours', noiseCancellation: 'Active', weight: '250g', multipoint: true },
    tags: ['sony', 'headphones', 'noise-cancelling'],
  },
  {
    externalId: 'tk-007',
    title: 'Apple AirPods Pro 2nd Gen',
    description:
      'Active noise cancellation, Adaptive Audio, Conversation Awareness, MagSafe USB-C charging case.',
    price: 24900,
    originalPrice: 26900,
    category: 'audio',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/61n7MpBGeBL._AC_SL1500_.jpg',
    rating: 4.8,
    reviewCount: 12453,
    stock: 300,
    isFeatured: false,
    specs: { type: 'In-ear', connectivity: 'Bluetooth 5.3', battery: '6 hours (30 with case)', anc: 'Active Noise Cancellation', spatialAudio: true, chip: 'H2' },
    tags: ['apple', 'airpods', 'earbuds', 'anc'],
  },
  {
    externalId: 'tk-012',
    title: 'Bose QuietComfort Ultra Earbuds',
    description:
      'Immersive Audio with head tracking, world-class ANC, CustomTune sound calibration, IPX4 rated.',
    price: 27900,
    originalPrice: 31900,
    category: 'audio',
    brand: 'Bose',
    imageUrl: 'https://m.media-amazon.com/images/I/511MML7u6GL._AC_.jpg',
    rating: 4.6,
    reviewCount: 1670,
    stock: 110,
    isFeatured: false,
    specs: { type: 'In-ear', connectivity: 'Bluetooth 5.3', battery: '6 hours (24 with case)', anc: 'Active Noise Cancellation', waterResistant: 'IPX4' },
    tags: ['bose', 'earbuds', 'anc', 'audio'],
  },
  {
    externalId: 'tk-120',
    title: 'boAt Airdopes 141 TWS',
    description:
      '42H playback, ENx noise cancellation for calls, low-latency BEAST mode, IPX4, Bluetooth 5.1.',
    price: 1299,
    originalPrice: 4490,
    category: 'audio',
    brand: 'boAt',
    imageUrl: 'https://m.media-amazon.com/images/I/615-1qhF7DL._SL1500_.jpg',
    rating: 4.1,
    reviewCount: 45230,
    stock: 500,
    isFeatured: false,
    specs: { type: 'In-ear TWS', connectivity: 'Bluetooth 5.1', battery: '42 hours total', waterResistant: 'IPX4' },
    tags: ['boat', 'earbuds', 'budget', 'tws'],
  },
  {
    externalId: 'tk-121',
    title: 'JBL Tune 510BT Headphones',
    description:
      'Pure Bass sound, 40-hour battery, foldable on-ear design, multipoint connection, USB-C fast charge.',
    price: 3499,
    originalPrice: 4999,
    category: 'audio',
    brand: 'JBL',
    imageUrl: 'https://m.media-amazon.com/images/I/51JihIUuhxL._AC_.jpg',
    rating: 4.4,
    reviewCount: 28100,
    stock: 400,
    isFeatured: false,
    specs: { type: 'On-ear', connectivity: 'Bluetooth 5.0', battery: '40 hours', foldable: true },
    tags: ['jbl', 'headphones', 'budget'],
  },
  {
    externalId: 'tk-122',
    title: 'Sony WF-C700N Earbuds',
    description:
      'Compact true-wireless with Active Noise Cancellation, 15-hour battery, IPX4, multipoint, DSEE upscaling.',
    price: 8990,
    originalPrice: 11990,
    category: 'audio',
    brand: 'Sony',
    imageUrl: 'https://m.media-amazon.com/images/I/51B6+Iyd3ML._AC_.jpg',
    rating: 4.4,
    reviewCount: 3210,
    stock: 220,
    isFeatured: false,
    specs: { type: 'In-ear TWS', connectivity: 'Bluetooth 5.2', battery: '15 hours total', anc: 'Active', waterResistant: 'IPX4' },
    tags: ['sony', 'earbuds', 'anc', 'value'],
  },
  {
    externalId: 'tk-123',
    title: 'JBL Flip 6 Bluetooth Speaker',
    description:
      'Bold JBL Pro Sound, IP67 waterproof & dustproof, 12-hour playtime, PartyBoost, racetrack driver.',
    price: 9999,
    originalPrice: 12999,
    category: 'audio',
    brand: 'JBL',
    imageUrl: 'https://m.media-amazon.com/images/I/81K7swplL7L._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 9870,
    stock: 180,
    isFeatured: false,
    specs: { type: 'Portable speaker', connectivity: 'Bluetooth 5.1', battery: '12 hours', waterproof: 'IP67' },
    tags: ['jbl', 'speaker', 'portable'],
  },
  {
    externalId: 'tk-124',
    title: 'Marshall Emberton II Speaker',
    description:
      'Iconic Marshall design, True Stereophonic 360° sound, 30+ hour playtime, IP67, USB-C.',
    price: 14999,
    originalPrice: 17999,
    category: 'audio',
    brand: 'Marshall',
    imageUrl: 'https://m.media-amazon.com/images/I/81N1pwfMR6L._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 2140,
    stock: 90,
    isFeatured: false,
    specs: { type: 'Portable speaker', connectivity: 'Bluetooth 5.1', battery: '30+ hours', waterproof: 'IP67' },
    tags: ['marshall', 'speaker', 'premium'],
  },

  // ─────────────── TABLETS ───────────────
  {
    externalId: 'tk-005',
    title: 'iPad Pro 12.9" M2 Wi-Fi',
    description:
      'M2 chip, 256GB storage, Liquid Retina XDR display with ProMotion 120Hz, Apple Pencil 2 support.',
    price: 112900,
    originalPrice: 119900,
    category: 'tablets',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/81k6ugO1HNS._AC_.jpg',
    rating: 4.8,
    reviewCount: 3201,
    stock: 80,
    isFeatured: false,
    specs: { processor: 'Apple M2', storage: '256GB', display: '12.9" Liquid Retina XDR', refresh: '120Hz ProMotion', battery: '10 hours', connectivity: 'Wi-Fi 6E' },
    tags: ['apple', 'ipad', 'tablet', 'creative'],
  },
  {
    externalId: 'tk-130',
    title: 'Apple iPad 10th Gen Wi-Fi',
    description:
      'A14 Bionic, 64GB, 10.9" Liquid Retina, USB-C, Touch ID, landscape FaceTime camera.',
    price: 34900,
    originalPrice: 39900,
    category: 'tablets',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/61A9uyV2HZL._AC_.jpg',
    rating: 4.6,
    reviewCount: 2890,
    stock: 140,
    isFeatured: false,
    specs: { processor: 'A14 Bionic', storage: '64GB', display: '10.9" Liquid Retina', battery: '10 hours', connectivity: 'Wi-Fi 6' },
    tags: ['apple', 'ipad', 'tablet'],
  },
  {
    externalId: 'tk-131',
    title: 'iPad Air 11" M2 Wi-Fi',
    description:
      'Apple M2 chip, 128GB, 11" Liquid Retina, supports Apple Pencil Pro, Touch ID, USB-C.',
    price: 59900,
    originalPrice: 64900,
    category: 'tablets',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/81lyb6WDPHL._AC_.jpg',
    rating: 4.7,
    reviewCount: 1210,
    stock: 95,
    isFeatured: true,
    specs: { processor: 'Apple M2', storage: '128GB', display: '11" Liquid Retina', battery: '10 hours', connectivity: 'Wi-Fi 6E' },
    tags: ['apple', 'ipad', 'tablet'],
  },
  {
    externalId: 'tk-132',
    title: 'Samsung Galaxy Tab S9 FE',
    description:
      'Exynos 1380, 8GB RAM, 128GB, 10.9" 90Hz LCD, IP68 water resistant, S Pen included.',
    price: 39999,
    originalPrice: 46999,
    category: 'tablets',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/61Qac0YD4SL.jpg',
    rating: 4.4,
    reviewCount: 1560,
    stock: 110,
    isFeatured: false,
    specs: { processor: 'Exynos 1380', ram: '8GB', storage: '128GB', display: '10.9" 90Hz', battery: '8000mAh', sPen: true },
    tags: ['samsung', 'tablet', 'android'],
  },
  {
    externalId: 'tk-133',
    title: 'Xiaomi Pad 6',
    description:
      'Snapdragon 870, 8GB RAM, 128GB, 11" 144Hz WQHD+, quad speakers, 8840mAh, 33W charging.',
    price: 26999,
    originalPrice: 31999,
    category: 'tablets',
    brand: 'Xiaomi',
    imageUrl: 'https://m.media-amazon.com/images/I/51wp5P394mL.jpg',
    rating: 4.4,
    reviewCount: 4320,
    stock: 130,
    isFeatured: false,
    specs: { processor: 'Snapdragon 870', ram: '8GB', storage: '128GB', display: '11" 144Hz WQHD+', battery: '8840mAh' },
    tags: ['xiaomi', 'tablet', 'value'],
  },
  {
    externalId: 'tk-134',
    title: 'Samsung Galaxy Tab A9+',
    description:
      'Snapdragon 695, 8GB RAM, 128GB, 11" 90Hz display, quad Dolby Atmos speakers, 7040mAh.',
    price: 17999,
    originalPrice: 21999,
    category: 'tablets',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/81bxxUTzmkL._AC_.jpg',
    rating: 4.3,
    reviewCount: 3870,
    stock: 200,
    isFeatured: false,
    specs: { processor: 'Snapdragon 695', ram: '8GB', storage: '128GB', display: '11" 90Hz', battery: '7040mAh' },
    tags: ['samsung', 'tablet', 'budget'],
  },

  // ─────────────── TELEVISIONS ───────────────
  {
    externalId: 'tk-008',
    title: 'Samsung 55" Neo QLED 4K Smart TV',
    description:
      'Neo QLED with Mini LED, Quantum HDR 32x, 120Hz, Game Mode Pro, Object Tracking Sound+.',
    price: 89990,
    originalPrice: 109990,
    category: 'televisions',
    brand: 'Samsung',
    imageUrl:
      'https://m.media-amazon.com/images/I/91blSirEjOL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 2109,
    stock: 60,
    isFeatured: true,
    specs: { size: '55 inches', resolution: '4K UHD', displayTech: 'Neo QLED Mini LED', refresh: '120Hz', hdr: 'Quantum HDR 32x', smartOs: 'Tizen' },
    tags: ['samsung', 'tv', '4k', 'qled'],
  },
  {
    externalId: 'tk-140',
    title: 'Redmi 43" 4K Smart Fire TV',
    description:
      '43-inch 4K Ultra HD LED, HDR10, Dolby Vision & Atmos, Fire TV OS, far-field voice remote.',
    price: 24999,
    originalPrice: 32999,
    category: 'televisions',
    brand: 'Redmi',
    imageUrl: 'https://m.media-amazon.com/images/I/819Lw2PE8tL._AC_.jpg',
    rating: 4.3,
    reviewCount: 12400,
    stock: 150,
    isFeatured: false,
    specs: { size: '43 inches', resolution: '4K UHD', hdr: 'Dolby Vision', refresh: '60Hz', smartOs: 'Fire TV' },
    tags: ['redmi', 'tv', '4k', 'budget'],
  },
  {
    externalId: 'tk-141',
    title: 'TCL 50" QLED 4K Google TV',
    description:
      '50-inch QLED 4K, 120Hz Game Accelerator, Dolby Vision-Atmos, hands-free Google TV, MEMC.',
    price: 33990,
    originalPrice: 54990,
    category: 'televisions',
    brand: 'TCL',
    imageUrl: 'https://m.media-amazon.com/images/I/71LfVIJvgxL.jpg',
    rating: 4.2,
    reviewCount: 5320,
    stock: 100,
    isFeatured: false,
    specs: { size: '50 inches', resolution: '4K UHD', displayTech: 'QLED', refresh: '120Hz', smartOs: 'Google TV' },
    tags: ['tcl', 'tv', 'qled', '4k'],
  },
  {
    externalId: 'tk-142',
    title: 'Sony Bravia 55" 4K Google TV',
    description:
      'X1 4K Processor, TRILUMINOS PRO, Dolby Vision-Atmos, Google TV, perfect for PS5 with HDMI 2.1.',
    price: 64990,
    originalPrice: 84990,
    category: 'televisions',
    brand: 'Sony',
    imageUrl: 'https://m.media-amazon.com/images/I/71waaSZrdIL._AC_SL1500_.jpg',
    rating: 4.5,
    reviewCount: 2870,
    stock: 70,
    isFeatured: false,
    specs: { size: '55 inches', resolution: '4K UHD', processor: 'X1 4K', hdr: 'Dolby Vision', smartOs: 'Google TV' },
    tags: ['sony', 'tv', '4k', 'bravia'],
  },
  {
    externalId: 'tk-143',
    title: 'LG 55" OLED evo C4 4K TV',
    description:
      'Self-lit OLED evo, α9 AI Processor Gen7, 144Hz, Dolby Vision-Atmos, perfect blacks, webOS.',
    price: 119990,
    originalPrice: 159990,
    category: 'televisions',
    brand: 'LG',
    imageUrl: 'https://m.media-amazon.com/images/I/81iSxTSYQ2L.jpg',
    rating: 4.7,
    reviewCount: 1430,
    stock: 45,
    isFeatured: true,
    specs: { size: '55 inches', resolution: '4K UHD', displayTech: 'OLED evo', refresh: '144Hz', hdr: 'Dolby Vision', smartOs: 'webOS' },
    tags: ['lg', 'tv', 'oled', '4k'],
  },
  {
    externalId: 'tk-144',
    title: 'LG 65" OLED evo C4 4K TV',
    description:
      'Massive 65" OLED evo, α9 AI Processor Gen7, 144Hz gaming, Brightness Booster, Dolby Vision IQ.',
    price: 184990,
    originalPrice: 249990,
    category: 'televisions',
    brand: 'LG',
    imageUrl: 'https://m.media-amazon.com/images/I/81QAq0+lmxL._AC_.jpg',
    rating: 4.8,
    reviewCount: 820,
    stock: 30,
    isFeatured: false,
    specs: { size: '65 inches', resolution: '4K UHD', displayTech: 'OLED evo', refresh: '144Hz', hdr: 'Dolby Vision IQ', smartOs: 'webOS' },
    tags: ['lg', 'tv', 'oled', 'premium'],
  },

  // ─────────────── COMPUTERS (GPU / DESKTOP / CPU) ───────────────
  {
    externalId: 'tk-004',
    title: 'NVIDIA GeForce RTX 4080 Super',
    description:
      '16GB GDDR6X, DLSS 3.5, Ada Lovelace architecture, 4K gaming at ultra settings, PCIe 4.0.',
    price: 109999,
    originalPrice: 119999,
    category: 'computers',
    brand: 'NVIDIA',
    imageUrl: 'https://m.media-amazon.com/images/I/718OTOL3ddL._AC_.jpg',
    rating: 4.9,
    reviewCount: 1205,
    stock: 30,
    isFeatured: true,
    specs: { vram: '16GB GDDR6X', architecture: 'Ada Lovelace', tdp: '320W', interface: 'PCIe 4.0', outputs: '3x DP, 1x HDMI 2.1' },
    tags: ['nvidia', 'gpu', 'gaming', '4k'],
  },
  {
    externalId: 'tk-150',
    title: 'NVIDIA GeForce RTX 4060 8GB',
    description:
      '8GB GDDR6, DLSS 3, Ada Lovelace, excellent 1080p/1440p gaming, 115W efficient design.',
    price: 31990,
    originalPrice: 36990,
    category: 'computers',
    brand: 'NVIDIA',
    imageUrl: 'https://m.media-amazon.com/images/I/712xE975t1L._AC_.jpg',
    rating: 4.5,
    reviewCount: 2140,
    stock: 90,
    isFeatured: false,
    specs: { vram: '8GB GDDR6', architecture: 'Ada Lovelace', tdp: '115W', interface: 'PCIe 4.0' },
    tags: ['nvidia', 'gpu', 'gaming', '1080p'],
  },
  {
    externalId: 'tk-151',
    title: 'NVIDIA GeForce RTX 4070 Super',
    description:
      '12GB GDDR6X, DLSS 3.5, Ada Lovelace, high-refresh 1440p & entry 4K gaming, ray tracing.',
    price: 62990,
    originalPrice: 69990,
    category: 'computers',
    brand: 'NVIDIA',
    imageUrl: 'https://m.media-amazon.com/images/I/71qIJjDVfzL._AC_.jpg',
    rating: 4.7,
    reviewCount: 1530,
    stock: 60,
    isFeatured: false,
    specs: { vram: '12GB GDDR6X', architecture: 'Ada Lovelace', tdp: '220W', interface: 'PCIe 4.0' },
    tags: ['nvidia', 'gpu', 'gaming', '1440p'],
  },
  {
    externalId: 'tk-152',
    title: 'NVIDIA GeForce RTX 4090',
    description:
      '24GB GDDR6X, the ultimate GPU for 4K/8K gaming and AI workloads, DLSS 3.5, Ada Lovelace.',
    price: 199990,
    originalPrice: 219990,
    category: 'computers',
    brand: 'NVIDIA',
    imageUrl: 'https://m.media-amazon.com/images/I/61iSt9D6YvL._AC_UL320_.jpg',
    rating: 4.9,
    reviewCount: 640,
    stock: 18,
    isFeatured: true,
    specs: { vram: '24GB GDDR6X', architecture: 'Ada Lovelace', tdp: '450W', interface: 'PCIe 4.0' },
    tags: ['nvidia', 'gpu', '4k', 'flagship'],
  },
  {
    externalId: 'tk-153',
    title: 'Apple Mac mini M2',
    description:
      'Apple M2 chip, 8GB unified memory, 256GB SSD, compact desktop powerhouse, macOS, plenty of ports.',
    price: 59900,
    originalPrice: 64900,
    category: 'computers',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/61La8PAa42L._AC_SL1500_.jpg',
    rating: 4.8,
    reviewCount: 1980,
    stock: 75,
    isFeatured: false,
    specs: { processor: 'Apple M2', ram: '8GB', storage: '256GB SSD', os: 'macOS', ports: '2x Thunderbolt 4, HDMI, 2x USB-A' },
    tags: ['apple', 'desktop', 'mac', 'mini'],
  },
  {
    externalId: 'tk-154',
    title: 'Intel Core i7-14700K Processor',
    description:
      '20 cores (8P+12E), up to 5.6GHz, LGA1700, unlocked for overclocking, DDR5 & PCIe 5.0 support.',
    price: 37990,
    originalPrice: 44990,
    category: 'computers',
    brand: 'Intel',
    imageUrl: 'https://m.media-amazon.com/images/I/61C1DOLRK4L._AC_.jpg',
    rating: 4.7,
    reviewCount: 980,
    stock: 120,
    isFeatured: false,
    specs: { cores: '20 (8P+12E)', boostClock: '5.6GHz', socket: 'LGA1700', tdp: '125W' },
    tags: ['intel', 'cpu', 'processor'],
  },
  {
    externalId: 'tk-155',
    title: 'HP Victus Gaming Desktop',
    description:
      'Intel Core i5-13400F, 16GB RAM, 512GB SSD, NVIDIA RTX 4060, Windows 11, RGB tower.',
    price: 89990,
    originalPrice: 109990,
    category: 'computers',
    brand: 'HP',
    imageUrl: 'https://m.media-amazon.com/images/I/5171aeOxqmL._AC_SL1244_.jpg',
    rating: 4.4,
    reviewCount: 540,
    stock: 50,
    isFeatured: false,
    specs: { processor: 'Intel Core i5-13400F', ram: '16GB', storage: '512GB SSD', gpu: 'NVIDIA RTX 4060', os: 'Windows 11' },
    tags: ['hp', 'desktop', 'gaming'],
  },

  // ─────────────── CAMERAS ───────────────
  {
    externalId: 'tk-160',
    title: 'GoPro HERO12 Black',
    description:
      '5.3K60 video, HDR, HyperSmooth 6.0 stabilization, waterproof to 10m, 27MP photos.',
    price: 41990,
    originalPrice: 49000,
    category: 'cameras',
    brand: 'GoPro',
    imageUrl: 'https://m.media-amazon.com/images/I/518Rq390jRL.jpg',
    rating: 4.5,
    reviewCount: 3210,
    stock: 110,
    isFeatured: false,
    specs: { video: '5.3K60', photo: '27MP', stabilization: 'HyperSmooth 6.0', waterproof: '10m' },
    tags: ['gopro', 'camera', 'action'],
  },
  {
    externalId: 'tk-161',
    title: 'Canon EOS R50 Mirrorless',
    description:
      '24.2MP APS-C, 4K30 video, Dual Pixel CMOS AF II, RF-S 18-45mm kit lens, content creator ready.',
    price: 57990,
    originalPrice: 67995,
    category: 'cameras',
    brand: 'Canon',
    imageUrl: 'https://m.media-amazon.com/images/I/71QydeWkpQL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 1240,
    stock: 70,
    isFeatured: true,
    specs: { sensor: '24.2MP APS-C', video: '4K30', mount: 'RF', kitLens: '18-45mm', autofocus: 'Dual Pixel CMOS AF II' },
    tags: ['canon', 'camera', 'mirrorless'],
  },
  {
    externalId: 'tk-162',
    title: 'Sony Alpha ZV-E10 Vlog Camera',
    description:
      '24.2MP APS-C, 4K video, dedicated vlog features, flip-out screen, 16-50mm power zoom kit.',
    price: 62990,
    originalPrice: 74990,
    category: 'cameras',
    brand: 'Sony',
    imageUrl: 'https://m.media-amazon.com/images/I/71vsOfa6JXL._AC_.jpg',
    rating: 4.5,
    reviewCount: 1680,
    stock: 65,
    isFeatured: false,
    specs: { sensor: '24.2MP APS-C', video: '4K', mount: 'E', kitLens: '16-50mm', vlog: true },
    tags: ['sony', 'camera', 'vlog', 'mirrorless'],
  },
  {
    externalId: 'tk-163',
    title: 'Fujifilm X-T30 II Mirrorless',
    description:
      '26.1MP X-Trans CMOS 4, 4K30, classic Fuji film simulations, tilting touchscreen, 15-45mm kit.',
    price: 89990,
    originalPrice: 99999,
    category: 'cameras',
    brand: 'Fujifilm',
    imageUrl: 'https://m.media-amazon.com/images/I/815NDECHdCL._AC_.jpg',
    rating: 4.7,
    reviewCount: 760,
    stock: 40,
    isFeatured: false,
    specs: { sensor: '26.1MP X-Trans CMOS 4', video: '4K30', mount: 'X', kitLens: '15-45mm', filmSim: true },
    tags: ['fujifilm', 'camera', 'mirrorless'],
  },
  {
    externalId: 'tk-164',
    title: 'Sony Alpha A7C II Full-Frame',
    description:
      '33MP full-frame, AI autofocus, 4K60 video, in-body 5-axis stabilization, compact rangefinder body.',
    price: 169990,
    originalPrice: 199990,
    category: 'cameras',
    brand: 'Sony',
    imageUrl: 'https://m.media-amazon.com/images/I/61Ywoz077rL._AC_UF1000,1000_QL80_.jpg',
    rating: 4.8,
    reviewCount: 410,
    stock: 25,
    isFeatured: true,
    specs: { sensor: '33MP Full-Frame', video: '4K60', mount: 'E', stabilization: '5-axis IBIS', autofocus: 'AI-based' },
    tags: ['sony', 'camera', 'full-frame', 'professional'],
  },

  // ─────────────── ACCESSORIES ───────────────
  {
    externalId: 'tk-009',
    title: 'Logitech MX Master 3S Mouse',
    description:
      'Ergonomic wireless mouse with MagSpeed scroll wheel, 8000 DPI, USB-C quick charge, multi-device.',
    price: 9495,
    originalPrice: 10995,
    category: 'accessories',
    brand: 'Logitech',
    imageUrl: 'https://m.media-amazon.com/images/I/61+OT7FPABL._AC_SL1500_.jpg',
    rating: 4.8,
    reviewCount: 4521,
    stock: 250,
    isFeatured: false,
    specs: { type: 'Wireless', dpi: '8000', battery: '70 days', connectivity: 'Bluetooth / USB Receiver', buttons: '7' },
    tags: ['logitech', 'mouse', 'productivity'],
  },
  {
    externalId: 'tk-010',
    title: 'Keychron K2 Pro Mechanical Keyboard',
    description:
      '75% layout wireless mechanical keyboard, hot-swappable switches, QMK/VIA, aluminum frame.',
    price: 13990,
    originalPrice: 15990,
    category: 'accessories',
    brand: 'Keychron',
    imageUrl: 'https://m.media-amazon.com/images/I/61fJx5N+eeL.jpg',
    rating: 4.7,
    reviewCount: 1820,
    stock: 90,
    isFeatured: false,
    specs: { layout: '75%', switches: 'Hot-swappable Gateron', connectivity: 'Bluetooth 5.1 / USB-C', battery: '4000 mAh' },
    tags: ['keychron', 'keyboard', 'mechanical'],
  },
  {
    externalId: 'tk-170',
    title: 'Logitech G502 HERO Gaming Mouse',
    description:
      'HERO 25K sensor, 11 programmable buttons, adjustable weights, LIGHTSYNC RGB, wired.',
    price: 3495,
    originalPrice: 5995,
    category: 'accessories',
    brand: 'Logitech',
    imageUrl: 'https://m.media-amazon.com/images/I/718b9wK3eaL._AC_.jpg',
    rating: 4.7,
    reviewCount: 15300,
    stock: 300,
    isFeatured: false,
    specs: { type: 'Wired', sensor: 'HERO 25K', dpi: '25600', buttons: '11', rgb: true },
    tags: ['logitech', 'mouse', 'gaming'],
  },
  {
    externalId: 'tk-171',
    title: 'Samsung T7 Portable SSD 1TB',
    description:
      'USB 3.2 Gen2, up to 1050MB/s, shock-resistant aluminium, password protection, pocket-sized.',
    price: 8990,
    originalPrice: 13999,
    category: 'accessories',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/41Moqv3vigL.jpg',
    rating: 4.7,
    reviewCount: 22100,
    stock: 260,
    isFeatured: false,
    specs: { capacity: '1TB', interface: 'USB 3.2 Gen2', speed: '1050MB/s', encryption: 'AES 256-bit' },
    tags: ['samsung', 'ssd', 'storage'],
  },
  {
    externalId: 'tk-172',
    title: 'Anker 737 Power Bank 24000mAh',
    description:
      '24000mAh, 140W max output, USB-C PD 3.1, smart digital display, charges laptops & phones fast.',
    price: 9999,
    originalPrice: 13999,
    category: 'accessories',
    brand: 'Anker',
    imageUrl: 'https://m.media-amazon.com/images/I/61FeCECR4wL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 6700,
    stock: 190,
    isFeatured: false,
    specs: { capacity: '24000mAh', output: '140W', ports: '2x USB-C, 1x USB-A', display: 'Digital' },
    tags: ['anker', 'powerbank', 'charging'],
  },
  {
    externalId: 'tk-173',
    title: 'LG UltraGear 27" 144Hz Monitor',
    description:
      '27" QHD (2560x1440) IPS, 144Hz, 1ms, HDR10, AMD FreeSync, sRGB 99%, gaming monitor.',
    price: 22990,
    originalPrice: 29999,
    category: 'accessories',
    brand: 'LG',
    imageUrl: 'https://m.media-amazon.com/images/I/81MinBCfJtL._AC_.jpg',
    rating: 4.6,
    reviewCount: 3120,
    stock: 100,
    isFeatured: false,
    specs: { size: '27"', resolution: 'QHD 2560x1440', refresh: '144Hz', panel: 'IPS', responseTime: '1ms' },
    tags: ['lg', 'monitor', 'gaming'],
  },
  {
    externalId: 'tk-174',
    title: 'Dell 27" FHD IPS Monitor S2725HS',
    description:
      '27" Full HD IPS, 100Hz, AMD FreeSync, built-in speakers, height-adjustable stand, slim bezels.',
    price: 12990,
    originalPrice: 17999,
    category: 'accessories',
    brand: 'Dell',
    imageUrl: 'https://m.media-amazon.com/images/I/71Cn8N4oo4L._AC_.jpg',
    rating: 4.5,
    reviewCount: 2540,
    stock: 140,
    isFeatured: false,
    specs: { size: '27"', resolution: 'FHD 1920x1080', refresh: '100Hz', panel: 'IPS', speakers: true },
    tags: ['dell', 'monitor', 'office'],
  },

  // ─────────────── WEARABLES / ELECTRONICS ───────────────
  {
    externalId: 'tk-180',
    title: 'Apple Watch Series 9 GPS 41mm',
    description:
      'S9 SiP, Double Tap gesture, brighter Always-On Retina, blood oxygen, ECG, crash detection.',
    price: 41900,
    originalPrice: 45900,
    category: 'electronics',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/71sLCEpm9aL._AC_SL1500_.jpg',
    rating: 4.8,
    reviewCount: 5210,
    stock: 130,
    isFeatured: true,
    specs: { chip: 'S9 SiP', display: 'Always-On Retina', size: '41mm', health: 'ECG, SpO2', connectivity: 'GPS' },
    tags: ['apple', 'watch', 'wearable', 'smartwatch'],
  },
  {
    externalId: 'tk-181',
    title: 'Apple Watch SE 2nd Gen GPS 40mm',
    description:
      'S8 SiP, Retina display, crash & fall detection, sleep & heart rate tracking, swimproof.',
    price: 29900,
    originalPrice: 31900,
    category: 'electronics',
    brand: 'Apple',
    imageUrl:
      'https://m.media-amazon.com/images/I/51eCHChOrML._AC_SL1000_.jpg',
    rating: 4.7,
    reviewCount: 3890,
    stock: 150,
    isFeatured: false,
    specs: { chip: 'S8 SiP', display: 'Retina', size: '40mm', health: 'Heart rate, SpO2', connectivity: 'GPS' },
    tags: ['apple', 'watch', 'wearable', 'value'],
  },
  {
    externalId: 'tk-182',
    title: 'Samsung Galaxy Watch 6 40mm',
    description:
      'Exynos W930, Super AMOLED, rotating bezel UX, advanced sleep coaching, BIA body composition.',
    price: 28999,
    originalPrice: 33999,
    category: 'electronics',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/71stMHB6LKL._AC_.jpg',
    rating: 4.4,
    reviewCount: 2140,
    stock: 120,
    isFeatured: false,
    specs: { processor: 'Exynos W930', display: 'Super AMOLED', size: '40mm', health: 'ECG, BIA, sleep', os: 'Wear OS' },
    tags: ['samsung', 'watch', 'wearable'],
  },
  {
    externalId: 'tk-183',
    title: 'Garmin Venu 3 Smartwatch',
    description:
      'AMOLED display, up to 14-day battery, advanced sleep & energy tracking, built-in GPS, voice calls.',
    price: 44990,
    originalPrice: 49990,
    category: 'electronics',
    brand: 'Garmin',
    imageUrl: 'https://m.media-amazon.com/images/I/61qxUctPfLL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 980,
    stock: 70,
    isFeatured: false,
    specs: { display: 'AMOLED', battery: '14 days', gps: true, health: 'Sleep, HRV, stress' },
    tags: ['garmin', 'watch', 'fitness'],
  },
  {
    externalId: 'tk-184',
    title: 'Amazfit GTR 4 Smartwatch',
    description:
      '1.43" AMOLED, dual-band GPS, 14-day battery, 150+ sports modes, Alexa built-in, Bluetooth calls.',
    price: 12999,
    originalPrice: 19999,
    category: 'electronics',
    brand: 'Amazfit',
    imageUrl: 'https://m.media-amazon.com/images/I/61J15V+8FIL._AC_.jpg',
    rating: 4.4,
    reviewCount: 4310,
    stock: 200,
    isFeatured: false,
    specs: { display: '1.43" AMOLED', battery: '14 days', gps: 'Dual-band', sports: '150+ modes' },
    tags: ['amazfit', 'watch', 'fitness', 'value'],
  },
  {
    externalId: 'tk-185',
    title: 'Noise ColorFit Pro 5 Smartwatch',
    description:
      '1.85" AMOLED, Bluetooth calling, 100+ sports modes, SpO2 & heart rate, 7-day battery.',
    price: 2499,
    originalPrice: 5999,
    category: 'electronics',
    brand: 'Noise',
    imageUrl: 'https://m.media-amazon.com/images/I/618sHIqH+VL._SX679_.jpg',
    rating: 4.1,
    reviewCount: 18700,
    stock: 400,
    isFeatured: false,
    specs: { display: '1.85" AMOLED', battery: '7 days', calling: true, health: 'SpO2, HR' },
    tags: ['noise', 'watch', 'budget'],
  },

  // ─────────────── EXPANSION BATCH 2 ───────────────
  {
    externalId: 'tk-200',
    title: 'ASUS Vivobook 16 Intel Core i5',
    description:
      'Intel Core i5-12500H, 16GB RAM, 512GB SSD, 16" WUXGA display, backlit keyboard, Windows 11.',
    price: 54990,
    originalPrice: 68990,
    category: 'laptops',
    brand: 'ASUS',
    imageUrl: 'https://m.media-amazon.com/images/I/71fWxnr0miL._SL1500_.jpg',
    rating: 4.3,
    reviewCount: 1340,
    stock: 120,
    isFeatured: false,
    specs: { processor: 'Intel Core i5-12500H', ram: '16GB', storage: '512GB SSD', display: '16" WUXGA', battery: '9 hours', os: 'Windows 11' },
    tags: ['asus', 'laptop', 'value'],
  },
  {
    externalId: 'tk-201',
    title: 'MSI Katana 15 RTX 4070',
    description:
      'Intel Core i7-13620H, 16GB DDR5, 1TB SSD, NVIDIA RTX 4070 8GB, 15.6" 144Hz FHD gaming laptop.',
    price: 124990,
    originalPrice: 149990,
    category: 'laptops',
    brand: 'MSI',
    imageUrl: 'https://m.media-amazon.com/images/I/81-3FfpcwML._AC_.jpg',
    rating: 4.5,
    reviewCount: 720,
    stock: 45,
    isFeatured: true,
    specs: { processor: 'Intel Core i7-13620H', ram: '16GB DDR5', storage: '1TB SSD', gpu: 'NVIDIA RTX 4070 8GB', display: '15.6" 144Hz FHD', os: 'Windows 11' },
    tags: ['msi', 'laptop', 'gaming'],
  },
  {
    externalId: 'tk-202',
    title: 'Apple MacBook Pro 16" M3 Pro',
    description:
      'Apple M3 Pro chip, 18GB RAM, 512GB SSD, 16.2" Liquid Retina XDR, up to 22-hour battery.',
    price: 199900,
    originalPrice: 249900,
    category: 'laptops',
    brand: 'Apple',
    imageUrl: 'https://m.media-amazon.com/images/I/61aUBxqc5PL._AC_SL1500_.jpg',
    rating: 4.9,
    reviewCount: 980,
    stock: 30,
    isFeatured: true,
    specs: { processor: 'Apple M3 Pro', ram: '18GB', storage: '512GB SSD', display: '16.2" Liquid Retina XDR', battery: '22 hours', os: 'macOS' },
    tags: ['apple', 'laptop', 'premium', 'pro'],
  },
  {
    externalId: 'tk-203',
    title: 'Samsung Galaxy A35 5G',
    description:
      'Exynos 1380, 8GB RAM, 128GB, 50MP OIS triple camera, 6.6" Super AMOLED 120Hz, IP67.',
    price: 30999,
    originalPrice: 34999,
    category: 'smartphones',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/61aUBxqc5PL._AC_SL1500_.jpg',
    rating: 4.3,
    reviewCount: 2640,
    stock: 180,
    isFeatured: false,
    specs: { processor: 'Exynos 1380', ram: '8GB', storage: '128GB', display: '6.6" Super AMOLED 120Hz', camera: '50MP OIS', battery: '5000mAh' },
    tags: ['samsung', 'smartphone', 'mid-range'],
  },
  {
    externalId: 'tk-204',
    title: 'iQOO Neo 9 Pro 5G',
    description:
      'Snapdragon 8 Gen 2, 12GB RAM, 256GB, 50MP Sony IMX920 OIS, 6.78" 144Hz AMOLED, 120W charging.',
    price: 38999,
    originalPrice: 44999,
    category: 'smartphones',
    brand: 'iQOO',
    imageUrl: 'https://m.media-amazon.com/images/I/611rQWZa5rL._SL1200_.jpg',
    rating: 4.4,
    reviewCount: 3120,
    stock: 140,
    isFeatured: false,
    specs: { processor: 'Snapdragon 8 Gen 2', ram: '12GB', storage: '256GB', display: '6.78" 144Hz AMOLED', camera: '50MP OIS', battery: '5160mAh' },
    tags: ['iqoo', 'smartphone', 'performance'],
  },
  {
    externalId: 'tk-205',
    title: 'Samsung Galaxy Z Flip 5',
    description:
      'Snapdragon 8 Gen 2, 8GB RAM, 256GB, foldable 6.7" FHD+ 120Hz, large 3.4" Flex Window cover screen.',
    price: 89999,
    originalPrice: 109999,
    category: 'smartphones',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/61kF9bAmg4L._AC_.jpg',
    rating: 4.5,
    reviewCount: 1450,
    stock: 70,
    isFeatured: true,
    specs: { processor: 'Snapdragon 8 Gen 2', ram: '8GB', storage: '256GB', display: '6.7" Foldable FHD+ 120Hz', camera: '12MP + 12MP', battery: '3700mAh' },
    tags: ['samsung', 'smartphone', 'foldable'],
  },
  {
    externalId: 'tk-206',
    title: 'iPhone 16 Pro 256GB',
    description:
      'A18 Pro chip, 6.3" Super Retina XDR, 48MP Fusion camera, 5x telephoto, titanium, Camera Control.',
    price: 119900,
    originalPrice: 124900,
    category: 'smartphones',
    brand: 'Apple',
    imageUrl: 'https://m.media-amazon.com/images/I/61JvFLHZ6NL.jpg',
    rating: 4.9,
    reviewCount: 2210,
    stock: 80,
    isFeatured: true,
    specs: { processor: 'A18 Pro', ram: '8GB', storage: '256GB', display: '6.3" Super Retina XDR', camera: '48MP + 48MP + 12MP', battery: '3582mAh' },
    tags: ['apple', 'iphone', 'flagship'],
  },
  {
    externalId: 'tk-207',
    title: 'Sennheiser Momentum 4 Wireless',
    description:
      'Audiophile sound, adaptive noise cancellation, 60-hour battery, premium comfort, aptX Adaptive.',
    price: 29990,
    originalPrice: 34990,
    category: 'audio',
    brand: 'Sennheiser',
    imageUrl: 'https://m.media-amazon.com/images/I/61kF9bAmg4L._AC_.jpg',
    rating: 4.6,
    reviewCount: 2870,
    stock: 90,
    isFeatured: false,
    specs: { type: 'Over-ear', connectivity: 'Bluetooth 5.2', battery: '60 hours', noiseCancellation: 'Adaptive', codec: 'aptX Adaptive' },
    tags: ['sennheiser', 'headphones', 'audiophile'],
  },
  {
    externalId: 'tk-208',
    title: 'boAt Rockerz 450 Headphones',
    description:
      'On-ear Bluetooth headphones, 15-hour playback, 40mm drivers, lightweight, dual connectivity.',
    price: 1499,
    originalPrice: 3990,
    category: 'audio',
    brand: 'boAt',
    imageUrl: 'https://m.media-amazon.com/images/I/61JvFLHZ6NL.jpg',
    rating: 4.2,
    reviewCount: 89200,
    stock: 500,
    isFeatured: false,
    specs: { type: 'On-ear', connectivity: 'Bluetooth 5.0', battery: '15 hours', drivers: '40mm' },
    tags: ['boat', 'headphones', 'budget'],
  },
  {
    externalId: 'tk-209',
    title: 'OnePlus Pad 2',
    description:
      'Snapdragon 8 Gen 3, 8GB RAM, 128GB, 12.1" 144Hz 3K display, 9510mAh, 67W SuperVOOC, Dolby Atmos.',
    price: 39999,
    originalPrice: 44999,
    category: 'tablets',
    brand: 'OnePlus',
    imageUrl: 'https://m.media-amazon.com/images/I/61xavUupweL.jpg',
    rating: 4.4,
    reviewCount: 980,
    stock: 100,
    isFeatured: false,
    specs: { processor: 'Snapdragon 8 Gen 3', ram: '8GB', storage: '128GB', display: '12.1" 144Hz 3K', battery: '9510mAh' },
    tags: ['oneplus', 'tablet', 'android'],
  },
  {
    externalId: 'tk-210',
    title: 'Samsung Galaxy Tab S9',
    description:
      'Snapdragon 8 Gen 2, 8GB RAM, 128GB, 11" Dynamic AMOLED 2X 120Hz, IP68, S Pen included.',
    price: 72999,
    originalPrice: 84999,
    category: 'tablets',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/618Acjb5AhL._AC_.jpg',
    rating: 4.6,
    reviewCount: 760,
    stock: 65,
    isFeatured: true,
    specs: { processor: 'Snapdragon 8 Gen 2', ram: '8GB', storage: '128GB', display: '11" AMOLED 2X 120Hz', battery: '8400mAh', sPen: true },
    tags: ['samsung', 'tablet', 'premium'],
  },
  {
    externalId: 'tk-211',
    title: 'OnePlus 55" QLED 4K Google TV',
    description:
      '55-inch QLED 4K, 120Hz, Dolby Vision-Atmos, 30W quad speakers, hands-free Google TV.',
    price: 42999,
    originalPrice: 59999,
    category: 'televisions',
    brand: 'OnePlus',
    imageUrl: 'https://m.media-amazon.com/images/I/71tfi6iFPYL._AC_.jpg',
    rating: 4.4,
    reviewCount: 3210,
    stock: 90,
    isFeatured: false,
    specs: { size: '55 inches', resolution: '4K UHD', displayTech: 'QLED', refresh: '120Hz', smartOs: 'Google TV' },
    tags: ['oneplus', 'tv', 'qled', '4k'],
  },
  {
    externalId: 'tk-212',
    title: 'Samsung 65" Crystal 4K Smart TV',
    description:
      '65-inch Crystal UHD 4K, Dynamic Crystal Color, HDR10+, Q-Symphony, Tizen smart TV with gaming hub.',
    price: 74990,
    originalPrice: 99990,
    category: 'televisions',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/618-e4au4QL._AC_SL1200_.jpg',
    rating: 4.4,
    reviewCount: 4120,
    stock: 60,
    isFeatured: false,
    specs: { size: '65 inches', resolution: '4K UHD', displayTech: 'Crystal UHD', hdr: 'HDR10+', smartOs: 'Tizen' },
    tags: ['samsung', 'tv', '4k'],
  },
  {
    externalId: 'tk-213',
    title: 'AMD Ryzen 7 7800X3D Processor',
    description:
      '8 cores / 16 threads, 3D V-Cache, up to 5.0GHz, AM5, the best CPU for gaming, DDR5 & PCIe 5.0.',
    price: 34990,
    originalPrice: 43990,
    category: 'computers',
    brand: 'AMD',
    imageUrl: 'https://m.media-amazon.com/images/I/61QON-Ik7OL._AC_SL1500_.jpg',
    rating: 4.9,
    reviewCount: 2310,
    stock: 110,
    isFeatured: true,
    specs: { cores: '8 / 16 threads', boostClock: '5.0GHz', socket: 'AM5', cache: '96MB 3D V-Cache', tdp: '120W' },
    tags: ['amd', 'cpu', 'gaming'],
  },
  {
    externalId: 'tk-214',
    title: 'NVIDIA GeForce RTX 4070 Ti Super',
    description:
      '16GB GDDR6X, DLSS 3.5, Ada Lovelace, excellent 1440p & 4K gaming, ray tracing, PCIe 4.0.',
    price: 84990,
    originalPrice: 94990,
    category: 'computers',
    brand: 'NVIDIA',
    imageUrl: 'https://m.media-amazon.com/images/I/81OQvV75qcL._AC_.jpg',
    rating: 4.7,
    reviewCount: 890,
    stock: 50,
    isFeatured: false,
    specs: { vram: '16GB GDDR6X', architecture: 'Ada Lovelace', tdp: '285W', interface: 'PCIe 4.0' },
    tags: ['nvidia', 'gpu', 'gaming', '4k'],
  },
  {
    externalId: 'tk-215',
    title: 'DJI Osmo Pocket 3 Creator Combo',
    description:
      '1-inch CMOS sensor, 4K120 video, 3-axis gimbal stabilization, 2" rotatable OLED, face tracking.',
    price: 69990,
    originalPrice: 75990,
    category: 'cameras',
    brand: 'DJI',
    imageUrl: 'https://m.media-amazon.com/images/I/7168GbCqlnL._AC_SL1400_.jpg',
    rating: 4.7,
    reviewCount: 1640,
    stock: 75,
    isFeatured: true,
    specs: { sensor: '1-inch CMOS', video: '4K120', stabilization: '3-axis gimbal', screen: '2" OLED' },
    tags: ['dji', 'camera', 'vlog', 'gimbal'],
  },
  {
    externalId: 'tk-216',
    title: 'Nikon Z fc Mirrorless Camera',
    description:
      '20.9MP APS-C, retro design, 4K30 video, vari-angle touchscreen, 16-50mm kit lens, Wi-Fi.',
    price: 84990,
    originalPrice: 99995,
    category: 'cameras',
    brand: 'Nikon',
    imageUrl: 'https://m.media-amazon.com/images/I/81yLdgsHwHL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 720,
    stock: 40,
    isFeatured: false,
    specs: { sensor: '20.9MP APS-C', video: '4K30', mount: 'Z', kitLens: '16-50mm', design: 'Retro' },
    tags: ['nikon', 'camera', 'mirrorless'],
  },
  {
    externalId: 'tk-217',
    title: 'SteelSeries Apex Pro TKL Keyboard',
    description:
      'Adjustable OmniPoint magnetic switches, OLED smart display, aluminum frame, per-key RGB, wired.',
    price: 19990,
    originalPrice: 23990,
    category: 'accessories',
    brand: 'SteelSeries',
    imageUrl: 'https://m.media-amazon.com/images/I/61x3QN9ZdCL._AC_SL1500_.jpg',
    rating: 4.6,
    reviewCount: 3210,
    stock: 110,
    isFeatured: false,
    specs: { layout: 'TKL', switches: 'OmniPoint adjustable', connectivity: 'USB-C', rgb: 'Per-key', display: 'OLED' },
    tags: ['steelseries', 'keyboard', 'gaming'],
  },
  {
    externalId: 'tk-218',
    title: 'Samsung 990 PRO 2TB NVMe SSD',
    description:
      'PCIe 4.0 M.2 NVMe, up to 7450MB/s read, ideal for gaming & content creation, Dynamic Thermal Guard.',
    price: 16990,
    originalPrice: 24999,
    category: 'accessories',
    brand: 'Samsung',
    imageUrl: 'https://m.media-amazon.com/images/I/81R7k0-HyVL._AC_.jpg',
    rating: 4.8,
    reviewCount: 8900,
    stock: 200,
    isFeatured: false,
    specs: { capacity: '2TB', interface: 'PCIe 4.0 NVMe', readSpeed: '7450MB/s', form: 'M.2 2280' },
    tags: ['samsung', 'ssd', 'storage', 'nvme'],
  },
  {
    externalId: 'tk-219',
    title: 'OnePlus Watch 2',
    description:
      'Snapdragon W5 + BES2700, 1.43" AMOLED, Wear OS, up to 100-hour battery, dual-frequency GPS.',
    price: 24999,
    originalPrice: 27999,
    category: 'electronics',
    brand: 'OnePlus',
    imageUrl: 'https://m.media-amazon.com/images/I/71I3RQGHDrL.jpg',
    rating: 4.4,
    reviewCount: 1120,
    stock: 130,
    isFeatured: false,
    specs: { display: '1.43" AMOLED', battery: '100 hours', os: 'Wear OS', gps: 'Dual-frequency', health: 'HR, SpO2, sleep' },
    tags: ['oneplus', 'watch', 'wearable'],
  },
];

export async function syncProductsFromAPI() {
  console.log('[Sync] Seeding curated TechKart catalog...');
  let count = 0;
  for (const p of SEEDED_PRODUCTS) {
    try {
      const product = await prisma.product.upsert({
        where: { externalId: p.externalId },
        update: {
          title: p.title,
          description: p.description,
          price: p.price,
          originalPrice: p.originalPrice ?? null,
          category: p.category,
          brand: p.brand,
          imageUrl: p.imageUrl,
          rating: p.rating,
          reviewCount: p.reviewCount,
          stock: p.stock,
          isFeatured: p.isFeatured ?? false,
          specs: p.specs,
          tags: p.tags,
        },
        create: p,
      });
      count++;

      const existing = await prisma.priceHistory.count({
        where: { productId: product.id },
      });
      if (existing < 5) {
        const base = Number(p.price);
        const entries = Array.from({ length: 90 }, (_, i) => ({
          productId: product.id,
          price: Math.round(base * (1 + (Math.random() - 0.45) * 0.12)),
          recordedAt: new Date(Date.now() - (90 - i) * 86400000),
          source: 'historical',
        }));
        await prisma.priceHistory.createMany({
          data: entries,
          skipDuplicates: true,
        });
      }
    } catch (e) {
      console.error(`[Sync] Failed for ${p.externalId}:`, e.message);
    }
  }
  // Remove legacy/junk products (e.g. old external-API rows with USD prices)
  // that are no longer part of the curated catalog.
  try {
    const keep = SEEDED_PRODUCTS.map((p) => p.externalId);
    const stale = await prisma.product.findMany({
      where: { externalId: { notIn: keep } },
      select: { id: true, title: true, externalId: true },
    });
    let removed = 0;
    for (const s of stale) {
      const isForeign = !s.externalId || !s.externalId.startsWith('tk-');
      const ordered = await prisma.orderItem.count({ where: { productId: s.id } });
      // Foreign junk (old external-API rows) is always purged, including any
      // test order references. A curated tk- product pulled from the list is
      // preserved if a customer actually ordered it (keep order history).
      if (!isForeign && ordered > 0) continue;
      if (isForeign && ordered > 0) {
        await prisma.orderItem.deleteMany({ where: { productId: s.id } });
      }
      await prisma.priceHistory.deleteMany({ where: { productId: s.id } });
      await prisma.wishlist.deleteMany({ where: { productId: s.id } });
      await prisma.cartItem.deleteMany({ where: { productId: s.id } });
      await prisma.product.delete({ where: { id: s.id } });
      removed++;
    }
    if (removed) console.log(`[Sync] Removed ${removed} legacy products.`);
  } catch (e) {
    console.error('[Sync] Cleanup skipped:', e.message);
  }

  console.log(`[Sync] Done. ${count}/${SEEDED_PRODUCTS.length} products in catalog.`);
}
